services:
  db:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=fundshare'
      - 'POSTGRES_PASSWORD=mypassword'
      - 'POSTGRES_USER=fundshare'
    volumes:
      - db:/data/db
  db-test:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=fundsharetest'
      - 'POSTGRES_PASSWORD=mypassword'
      - 'POSTGRES_USER=fundshare'
    volumes:
      - db-test:/data/db
  api:
    image: 'fundshare-backend'
    ports:
      - '8082:8080'
    depends_on:
      - db
volumes:
  db:
  db-test: