spring:
  config:
    import: .env.properties
  datasource:
    password: ${DB_PASS}
    url: jdbc:postgresql://db:5432/fundshare
    username: fundshare
  mail:
    password: ${MAIL_PASS}
cors:
  allowed-origins: https://fundshare.dviladev.com
auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    issuer: fundshare
  cookie:
    domain: fundshare.dviladev.com
    path: /
    secure: true
    httpOnly: true
    sameSite: Strict
minio:
  url: http://172.17.0.1:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
frontend:
  url: https://fundshare.dviladev.com
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
