spring:
  datasource:
    password: mypassword
    url: jdbc:postgresql://localhost:5436/fundshare
    username: fundshare
  application:
    name: fundshare-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: viladevapps@gmail.com
    password: iabn dhoj wpyc zzwu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  enabled: true
  subject:
    account-activation: Account Activation
    password-reset: Password Reset
  message:
    account-activation: Click on the link below to activate your account
    password-reset: Click on the link below to reset your password
auth:
  jwt:
    secret: mysecret
    expiration: 86400000
    issuer: fundshare
  cookie: 
    domain: 192.168.0.111
    path: /
    secure: false
    httpOnly: false
    sameSite: Lax
frontend:
  url: http://192.168.0.111:5173
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG