spring:
  datasource:
    password: mypassword
    url: jdbc:postgresql://localhost:5436/fundshare
    username: fundshare
  application:
    name: fundshare-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: viladevapps@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  allowed-origins: http://192.168.1.129:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: Accept,Content-Type,credentials,Content-Length,Accept-Encoding,X-API-CSRF,Authorization
  exposed-headers: Set-Cookie
  allow-credentials: true
mail:
  enabled: true
  subject:
    account-activation: Account Activation
    password-reset: Password Reset
  message:
    account-activation: Click on the link below to activate your FundShare account
    password-reset: Click on the link below to reset your password of your FundShare account
auth:
  jwt:
    secret: mysecret
    expiration: 86400000
    issuer: fundshare
  cookie:
    domain: 192.168.1.129
    path: /
    secure: false
    httpOnly: false
    sameSite: Lax
frontend:
  url: http://192.168.1.129:5173
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
