server:
  port: 8090
spring:
  datasource:
    password: mypassword
    url: jdbc:postgresql://localhost:5436/fundshare
    # url: jdbc:postgresql://db-e2e:5432/fundshare
    username: fundshare
  application:
    name: fundshare-api
 
mail:
  enabled: false
auth:
  cookie:
    domain: localhost
    path: /
    secure: false
    httpOnly: false
    sameSite: Lax
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
